In [1]:
import yfinance as yf
from datetime import date
from datetime import timedelta
from bs4 import BeautifulSoup
import requests
import smtplib
from email.mime.text import MIMEText

In [2]:
req=requests.get('https://www.borsaitaliana.it/borsa/etc-etn/scheda/GB00B15KXV33.html?lang=en')
r=req.text

In [3]:
soup = BeautifulSoup(r)

In [8]:
#Selecting the necessary data to be reported
openprice=float(soup.findAll("span", {"class": "t-text -right"})[0].text)
dayhigh=float(soup.findAll("span", {"class": "t-text -right"})[1].text)
daylow = float(soup.findAll("span", {"class": "t-text -right"})[2].text)
threshold=3.9703

In [5]:
gmail_user = 'simonas.audickas@gmail.com'
gmail_password = 'svedas1234'
    
sent_from = "Simonas Audickas <simonas.audickas@gmail.com"
to = ['info@teipsiko.lt']

In [11]:

if float(openprice) >= threshold:
    
    subject = 'Geros Naujienos'
    body = 'Akciju atidarymo kaina virsijo '+str(threshold)+'\n\n'+'Akciju kaina dabar yra '+str(openprice)+'.\n'+'Akciju auksciausias dienos taskas '+str(dayhigh)+'\n'+"Akciju zemiausias dienos taskas "+str(daylow)+'\n'+'https://www.borsaitaliana.it/borsa/etc-etn/scheda/GB00B15KXV33.html?lang=en'
    email_text = """From: %s
To: %s
Subject: %s

%s
""" % (sent_from, ", ".join(to), subject, body)
    try:
        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.ehlo()
        server.login(gmail_user, gmail_password)
        server.sendmail(sent_from, to, email_text)
        server.close()

        print ('Emailas issiustas')
    except:
        print ('Klaida...')
else:
    subject1 = 'Nieko gero del akciju'
    
    body1 = 'Akciju atidarymo kaina nevirsijo '+str(threshold)+'\n'+'Akciju kaina dabar yra '+str(openprice)+'.\n'+'Akciju auksciausias dienos taskas '+str(dayhigh)+'\n'+"Akciju zemiausias dienos taskas "+str(daylow)+'\n'+'https://www.borsaitaliana.it/borsa/etc-etn/scheda/GB00B15KXV33.html?lang=en'
            

    email_text1 = """From: %s
To: %s
Subject: %s

%s
""" % (sent_from, ", ".join(to), subject1, body1)
    try:
        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.ehlo()
        server.login(gmail_user, gmail_password)
        server.sendmail(sent_from, to, email_text1)
        server.close()

        print ('Emailas issiustas')
    except:
        print ('Klaida...')

Emailas issiustas

In [56]:
s=date.today()+timedelta(days=1)
print(s)

threshold=3.9703

2020-07-03

In [60]:
data = yf.download("CRUD.MI", start="2020-06-01", end=s)

[*********************100%***********************]  1 of 1 completed

In [61]:
data

              Open    High     Low   Close  Adj Close    Volume
Date
2020-06-01  3.0545  3.0700  2.9750  3.0055     3.0055   8858723
2020-06-02  3.0845  3.1330  3.0425  3.1120     3.1120   7740635
2020-06-03  3.2150  3.2195  3.0825  3.1470     3.1470  12890139
2020-06-04  3.1360  3.1520  3.0855  3.0930     3.0930   5408697
2020-06-05  3.1630  3.3470  3.1625  3.3170     3.3170  11812454
2020-06-08  3.3675  3.3840  3.2170  3.2405     3.2405  10379997
2020-06-09  3.2595  3.2695  3.1465  3.2020     3.2020   4852461
2020-06-10  3.2170  3.2535  3.1675  3.2415     3.2415   2684685
2020-06-11  3.1960  3.2265  3.0400  3.0600     3.0600   5702826
2020-06-12  2.9635  3.1230  2.9505  3.0795     3.0795   6008639
2020-06-15  2.9565  3.0750  2.9465  3.0745     3.0745   4965054
2020-06-16  3.1250  3.3105  3.1045  3.1800     3.1800   6122069
2020-06-17  3.1950  3.2795  3.1800  3.2200     3.2200   3621738
2020-06-18  3.2030  3.2800  3.1905  3.2800     3.2800   5217388
2020-06-19  3.3330  3.4125  3.3305  3.3890     3.3890   9685071
2020-06-22  3.3655  3.3885  3.3235  3.3810     3.3810   3535426
2020-06-23  3.3980  3.4800  3.3900  3.4435     3.4435   6733268
2020-06-24  3.3685  3.3900  3.1980  3.2100     3.2100   4927961
2020-06-25  3.1760  3.2640  3.1325  3.2170     3.2170   4639963
2020-06-26  3.2855  3.3140  3.1950  3.2120     3.2120   4346070

In [40]:
data.reset_index()
data['Data_lagged'] = data['Open'].shift(1)
data['Data_lead']= data['Open'].shift(-1)
data

,Open,High,Low,Close,Adj Close,Volume,Data_lagged,Data_lead
Date,,,,,,,,
2020-06-01,3.0545,3.0700,2.9750,3.0055,3.0055,8858723,NaN,3.0845
2020-06-02,3.0845,3.1330,3.0425,3.1120,3.1120,7740635,3.0545,3.2150
2020-06-03,3.2150,3.2195,3.0825,3.1470,3.1470,12890139,3.0845,3.1360
2020-06-04,3.1360,3.1520,3.0855,3.0930,3.0930,5408697,3.2150,3.1630
2020-06-05,3.1630,3.3470,3.1625,3.3170,3.3170,11812454,3.1360,3.3675
2020-06-08,3.3675,3.3840,3.2170,3.2405,3.2405,10379997,3.1630,3.2595
2020-06-09,3.2595,3.2695,3.1465,3.2020,3.2020,4852461,3.3675,3.2170
2020-06-10,3.2170,3.2535,3.1675,3.2415,3.2415,2684685,3.2595,3.1960
2020-06-11,3.1960,3.2265,3.0400,3.0600,3.0600,5702826,3.2170,2.9635
2020-06-12,2.9635,3.1230,2.9505,3.0795,3.0795,6008639,3.1960,2.9565
2020-06-15,2.9565,3.0750,2.9465,3.0745,3.0745,4965054,2.9635,3.1250
2020-06-16,3.1250,3.3105,3.1045,3.1800,3.1800,6122069,2.9565,3.1950
2020-06-17,3.1950,3.2795,3.1800,3.2200,3.2200,3621738,3.1250,3.2030
2020-06-18,3.2030,3.2800,3.1905,3.2800,3.2800,5217388,3.1950,3.3330
2020-06-19,3.3330,3.4125,3.3305,3.3890,3.3890,9685071,3.2030,3.3655
2020-06-22,3.3655,3.3885,3.3235,3.3810,3.3810,3535426,3.3330,3.3980
2020-06-23,3.3980,3.4800,3.3900,3.4435,3.4435,6733268,3.3655,3.3685
2020-06-24,3.3685,3.3900,3.1980,3.2100,3.2100,4927961,3.3980,3.1760
2020-06-25,3.1760,3.2640,3.1325,3.2170,3.2170,4639963,3.3685,3.2855
2020-06-26,3.2855,3.3140,3.1950,3.2120,3.2120,4346070,3.1760,3.3485
2020-07-01,3.3485,3.3925,3.3475,3.3925,3.3925,1125712,3.2855,NaN

Email sent!